#!/bin/bash
#$1 is firstname
#$2 is secondname
#note no code handles case so is case sensitive
#./findUser Jim Smith
#curl -i http://localhost:8181/users/findUser/$1/$2
curl -i http://localhost:8181/users/findUser/$1/$2
